name: chat_nik
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: '>=1.22.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  dart_webrtc: ^1.0.4
  flutter_webrtc: ^0.8.3
  shared_preferences: ^2.0.7
  http: ^0.13.3
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0

flutter:
  uses-material-design: true
