name: chat_nik
description: Serbian chat app.
version: 1.0.0+1

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: '>=1.22.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  dart_webrtc: ^1.0.4.
  flutter_webrtc: '>0.8.5 <0.9.0'
  shared_preferences: ^2.0.7
  http: ^0.13.3
  path_provider: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true